from fastapi import FastAPI, UploadFile, File, Form, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
from typing import Optional
from db_service import db_service
import os
import shutil

app = FastAPI(title="Alert Dashboard")

# Ensure templates and static dirs exist
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")
ALERTS_DIR = r"C:\Users\user\OneDrive\Desktop\Cilent Side\alert_img"

os.makedirs(TEMPLATES_DIR, exist_ok=True)
os.makedirs(STATIC_DIR, exist_ok=True)
os.makedirs(ALERTS_DIR, exist_ok=True)

app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
app.mount("/alert_img", StaticFiles(directory=ALERTS_DIR), name="alert_img")
templates = Jinja2Templates(directory=TEMPLATES_DIR)

class AlertResponse(BaseModel):
    id: str
    hash_id: str
    camera_source: str
    location: str
    object_detected: str
    alert_sent_to: str
    image_url: str
    created_at: str

class ConfigUpdate(BaseModel):
    storage_mode: str

@app.get("/api/config")
async def get_config():
    return {"storage_mode": db_service.get_storage_mode()}

@app.post("/api/config")
async def update_config(config: ConfigUpdate):
    if config.storage_mode not in ("local", "cloud"):
        return {"error": "Invalid storage mode. Must be 'local' or 'cloud'."}
    db_service.set_storage_mode(config.storage_mode)
    return {"message": "Configuration updated successfully", "storage_mode": config.storage_mode}

@app.post("/api/alerts")
async def create_alert(
    request: Request,
    hash_id: str = Form(...),
    camera_source: str = Form("Unknown"),
    location: str = Form("Unknown"),
    object_detected: str = Form("unknown"),
    alert_sent_to: str = Form(""),
    image: UploadFile = File(...)
):
    # Save uploaded image temporarily first
    temp_path = f"temp_{hash_id}_{image.filename}"
    with open(temp_path, "wb") as buffer:
        buffer.write(await image.read())

    # Get active storage mode
    storage_mode = db_service.get_storage_mode()
    image_url = None

    if storage_mode == "local":
        # Save to local static/alerts directory
        filename = f"{hash_id}_{image.filename}"
        local_dest = os.path.join(ALERTS_DIR, filename)
        shutil.copy(temp_path, local_dest)
        image_url = f"/alert_img/{filename}"
        
        # Clean up temp file
        if os.path.exists(temp_path):
            os.remove(temp_path)
    else:
        # Upload to Cloudinary
        uploaded_url = db_service.upload_to_cloudinary(temp_path)
        
        # Clean up temp file
        if os.path.exists(temp_path):
            os.remove(temp_path)
            
        if not uploaded_url:
            return {"error": "Failed to upload image to Cloudinary"}
        image_url = uploaded_url

    # Create Record in Database
    record = db_service.create_alert_record(
        hash_id=hash_id,
        camera_source=camera_source,
        location=location,
        object_detected=object_detected,
        alert_sent_to=alert_sent_to,
        image_url=image_url
    )

    if not record:
        return {"error": "Failed to create database record"}

    # Send Email Notification
    if alert_sent_to:
        local_image_path = None
        # If relative URL, it's local storage. Construct inline CID, otherwise use the Cloudinary URL.
        if image_url.startswith("/static") or image_url.startswith("/alert_img"):
            filename = os.path.basename(image_url)
            local_image_path = os.path.join(ALERTS_DIR, filename)
            img_email_url = "cid:threat_image"
        else:
            img_email_url = image_url

        from datetime import datetime
        det_time = datetime.now().strftime("%Y-%m-%d %I:%M:%S %p")
        subject = f"🚨 Warning: {object_detected.upper()} Detected at {location} 🚨"
        content = f"""
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: auto; border: 3px solid #dc2626; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(220, 38, 38, 0.15);">
            <div style="background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%); color: white; padding: 25px 20px; text-align: center;">
                <h1 style="margin: 0; font-size: 26px; text-transform: uppercase; letter-spacing: 1px; font-weight: 900;">⚠️ CRITICAL WARNING ⚠️</h1>
                <p style="margin: 8px 0 0; font-size: 16px; font-weight: bold; opacity: 0.9;">Immediate Action Required</p>
                <p>This is an automated alert generated by Threat Monitor.<br/>Please inspect the location immediately.</p>
            </div>
            <div style="padding: 24px; background-color: #fdf2f2; color: #111827; line-height: 1.6;">
                <h3 style="margin-top: 0; color: #991b1b; font-size: 20px; border-bottom: 2px solid #fee2e2; padding-bottom: 8px;">Threat Summary</h3>
                
                <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                    <tr style="border-bottom: 1px solid #fee2e2;">
                        <td style="padding: 8px 0; font-weight: bold; color: #4b5563; width: 140px;">Threat Detected:</td>
                        <td style="padding: 8px 0; font-size: 16px; font-weight: bold; color: #dc2626; text-transform: uppercase;">{object_detected}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #fee2e2;">
                        <td style="padding: 8px 0; font-weight: bold; color: #4b5563;">Location:</td>
                        <td style="padding: 8px 0; font-size: 15px; font-weight: 500;">{location}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #fee2e2;">
                        <td style="padding: 8px 0; font-weight: bold; color: #4b5563;">Camera Source:</td>
                        <td style="padding: 8px 0; font-size: 15px; text-transform: capitalize;">{camera_source}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #fee2e2;">
                        <td style="padding: 8px 0; font-weight: bold; color: #4b5563;">Detection Time:</td>
                        <td style="padding: 8px 0; font-size: 15px; color: #6b7280;">{det_time}</td>
                    </tr>
                </table>

                <div style="margin: 20px 0; border: 2px solid #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
                    <img src="{img_email_url}" alt="Threat Snapshot" style="width: 100%; display: block; max-height: 400px; object-fit: contain; background: #0b0f19;" />
                </div>
            </div>
        </div>
        """
        db_service.send_email_alert(alert_sent_to, subject, content, local_image_path)

    return {"message": "Alert created successfully", "id": record['$id']}

@app.get("/api/alerts")
async def get_alerts():
    documents = db_service.get_alerts()
    alerts = []
    for doc in documents:
        alerts.append({
            "id": doc.get("$id"),
            "hash_id": doc.get("hash_id"),
            "camera_source": doc.get("camera_source"),
            "location": doc.get("location"),
            "object_detected": doc.get("object_detected", "unknown"),
            "alert_sent_to": doc.get("alert_sent_to"),
            "image_url": doc.get("image_url"),
            "created_at": doc.get("$createdAt")
        })
    return alerts

@app.get("/", response_class=HTMLResponse)
async def dashboard(request: Request):
    return templates.TemplateResponse(request=request, name="index.html")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
